version: "3.8"

services:
  onlyoffice-documentserver:
    image: onlyoffice/documentserver
    container_name: onlyoffice-documentserver
    ports:
      - "8082:80"
    restart: unless-stopped
    volumes:
      - E:/docker/onlyoffice/onlyoffice-data:/var/www/onlyoffice/Data
      - E:/docker/onlyoffice/onlyoffice-logs:/var/log/onlyoffice
    environment:
      - JWT_ENABLED=false

  nginx:
    image: nginx:latest
    container_name: onlyoffice-nginx
    restart: unless-stopped
    ports:
      - "80:80"       # 反向代理对外端口80
    volumes:
      - E:/go代码/CollabDoc-go/docker/onlyoffice.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - onlyoffice-documentserver
